//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
    
        public int EmployeeID { get; set; }
        public string LastNameEmployee { get; set; }
        public string FirstNameEmployee { get; set; }
        public string EmailEmployee { get; set; }
        public string AddressEmployee { get; set; }
        public string TelephoneEmployee { get; set; }
        public Nullable<System.DateTime> BirthDateEmployee { get; set; }
        public Nullable<System.DateTime> HiringDateEmployee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }

        public virtual ApplicationUser User { get; set; }
    }
}
